"""remove_opportunity_type

Revision ID: 2b7b2946d131
Revises: 820ad32ce5ce
Create Date: 2016-02-03 11:18:33.362321

"""

# revision identifiers, used by Alembic.
revision = '2b7b2946d131'
down_revision = '820ad32ce5ce'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'opportunity_opportunity_type_id_fkey', 'opportunity', type_='foreignkey')
    op.drop_column('opportunity', 'opportunity_type_id')
    op.drop_table('opportunity_type')
    op.add_column('opportunity', sa.Column('submission_data', postgresql.JSON(), nullable=True))
    op.add_column('opportunity', sa.Column('type', sa.String(length=255), nullable=True))
    op.create_foreign_key('updated_by_id_fkey', 'question', 'users', ['updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key('created_by_id_fkey', 'question', 'users', ['created_by_id'], ['id'], use_alter=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_type',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('opportunity_response_instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], [u'users.id'], name=u'created_by_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by_id'], [u'users.id'], name=u'updated_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'opportunity_type_pkey')
    )
    op.drop_constraint('created_by_id_fkey', 'question', type_='foreignkey')
    op.drop_constraint('updated_by_id_fkey', 'question', type_='foreignkey')
    op.add_column('opportunity', sa.Column('opportunity_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'opportunity_opportunity_type_id_fkey', 'opportunity', 'opportunity_type', ['opportunity_type_id'], ['id'], ondelete=u'SET NULL')
    op.drop_column('opportunity', 'type')
    op.drop_column('opportunity', 'submission_data')
    ### end Alembic commands ###
